version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/scheduler/vaultoniq_front_clock_app
file_exists_behavior: OVERWRITE
hooks:
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 6000
      runas: ubuntu
